# Generated by Django 5.2.7 on 2025-12-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="callout",
            name="authorization",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="callout",
            name="callout_completed_by",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="callout",
            name="casing_size_inch",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="callout",
            name="completed_by_designation",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="callout",
            name="contact_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="callout",
            name="crew_required_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="callout",
            name="crew_required_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="callout",
            name="drillpipe_size_inch",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="callout",
            name="drop_gyro_gt_20",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="callout",
            name="drop_gyro_lt_20",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="callout",
            name="dry_hole_drop_gyro_system",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="callout",
            name="equipment_required_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="callout",
            name="equipment_required_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="callout",
            name="field_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="callout",
            name="ground_elevation_m",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="callout",
            name="h2s_level",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="callout",
            name="hole_section",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="callout",
            name="max_downhole_temp_c",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="callout",
            name="maximum_inclination_deg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="callout",
            name="memory_casing_slickline",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="callout",
            name="memory_drillpipe_slickline",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="callout",
            name="memory_pumpdown_survey",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="callout",
            name="minimum_id_inch",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="callout",
            name="motor_orientation_depth_m",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="callout",
            name="rig_floor_elevation_m",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="callout",
            name="service_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("wireline_gyro", "Wireline Gyro Surveys"),
                    ("memory_gyro", "Memory Gyro Surveys"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="callout",
            name="side_entry_sub_connection_size",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="callout",
            name="side_entry_sub_date_required",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="callout",
            name="side_entry_sub_size",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="callout",
            name="survey_end_depth_m",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="callout",
            name="survey_interval_m",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="callout",
            name="survey_start_depth_m",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="callout",
            name="ubho_sub_connection_size",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="callout",
            name="ubho_sub_date_required",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="callout",
            name="ubho_sub_size",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="callout",
            name="utm_easting",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="callout",
            name="utm_northing",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="callout",
            name="well_center_latitude",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="callout",
            name="well_center_longitude",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="callout",
            name="well_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="callout",
            name="well_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="callout",
            name="well_profile",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="callout",
            name="whipstock_orientation_depth_m",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="callout",
            name="wireline_casing_survey",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="callout",
            name="wireline_drillpipe_survey",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="callout",
            name="wireline_orientation_multishot_survey",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="callout",
            name="wireline_orientation_survey",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="callout",
            name="wireline_pumpdown_survey",
            field=models.BooleanField(default=False),
        ),
    ]
