# Generated by Django 5.2.7 on 2025-12-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_callout_authorization_callout_callout_completed_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="callout",
            name="well_center_latitude",
        ),
        migrations.RemoveField(
            model_name="callout",
            name="well_center_longitude",
        ),
        migrations.AddField(
            model_name="callout",
            name="well_center_lat_deg",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="callout",
            name="well_center_lat_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="callout",
            name="well_center_lat_sec",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="callout",
            name="well_center_lng_deg",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="callout",
            name="well_center_lng_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="callout",
            name="well_center_lng_sec",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
    ]
