# Generated by Django 5.2.7 on 2025-12-07 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_callout_well_center_latitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="HoleSection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Well",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("well_id", models.CharField(max_length=100, unique=True)),
                ("field_name", models.CharField(max_length=255)),
                ("well_center_lat_deg", models.IntegerField(blank=True, null=True)),
                ("well_center_lat_min", models.IntegerField(blank=True, null=True)),
                (
                    "well_center_lat_sec",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("well_center_lng_deg", models.IntegerField(blank=True, null=True)),
                ("well_center_lng_min", models.IntegerField(blank=True, null=True)),
                (
                    "well_center_lng_sec",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("utm_northing", models.CharField(blank=True, max_length=50)),
                ("utm_easting", models.CharField(blank=True, max_length=50)),
                (
                    "ground_elevation_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="callout",
            old_name="field_name",
            new_name="field_name_display",
        ),
        migrations.RenameField(
            model_name="callout",
            old_name="well_name",
            new_name="hole_section_display",
        ),
        migrations.RenameField(
            model_name="callout",
            old_name="well_id",
            new_name="well_id_display",
        ),
        migrations.AddField(
            model_name="callout",
            name="well_name_display",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="callout",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="callouts",
                to="core.customer",
            ),
        ),
        migrations.AlterField(
            model_name="callout",
            name="hole_section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="callouts",
                to="core.holesection",
            ),
        ),
        migrations.AddField(
            model_name="callout",
            name="well",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="callouts",
                to="core.well",
            ),
        ),
    ]
