# Generated by Django 5.2.7 on 2025-12-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_customer_holesection_well_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="callout",
            old_name="rig",
            new_name="rig_number",
        ),
        migrations.RemoveField(
            model_name="callout",
            name="client",
        ),
        migrations.RemoveField(
            model_name="callout",
            name="service_type",
        ),
        migrations.RemoveField(
            model_name="rig",
            name="client",
        ),
        migrations.RemoveField(
            model_name="well",
            name="field_name",
        ),
        migrations.AddField(
            model_name="callout",
            name="field_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="rig",
            name="rig_number",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
