# Generated by Django 5.2.7 on 2025-12-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_rig_callout_rig_number_remove_callout_client_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="holesection",
            name="sort_order",
        ),
    ]
