# Generated by Django 5.2.7 on 2025-12-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_holesection_sort_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rig",
            name="name",
        ),
    ]
