# Generated by Django 5.2.7 on 2025-12-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_rig_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="callout",
            name="field_name_display",
        ),
        migrations.AlterField(
            model_name="callout",
            name="rig_number",
            field=models.CharField(max_length=255),
        ),
    ]
