# Generated by Django 5.2.7 on 2025-12-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_callout_field_name_display_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="callout",
            name="callout_number",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="callout",
            name="callout_sequence",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
