# Generated by Django 5.2.7 on 2025-12-07 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_callout_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sro",
            name="planned_end",
        ),
        migrations.RemoveField(
            model_name="sro",
            name="planned_start",
        ),
        migrations.RemoveField(
            model_name="sro",
            name="service_type",
        ),
        migrations.AddField(
            model_name="sro",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sro",
            name="sro_sequence",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="sro",
            name="sro_number",
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
