# Generated by Django 5.2.7 on 2025-12-11 07:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_sro_planned_end_remove_sro_planned_start_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="callout",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("locked", "Locked"),
                    ("sro_activated", "SRO Activated"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schedule_sequence",
                    models.PositiveIntegerField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                (
                    "schedule_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "finance_priority",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "operations_priority",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "qa_priority",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "average_priority",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        editable=False,
                        max_digits=3,
                        null=True,
                    ),
                ),
                ("high_temp", models.BooleanField(blank=True, null=True)),
                ("pressure_risk", models.BooleanField(blank=True, null=True)),
                (
                    "difficulty_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("hse_risk", models.BooleanField(blank=True, null=True)),
                ("type_of_equipment", models.CharField(blank=True, max_length=255)),
                ("resource", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("planned", "Planned"),
                            ("approved", "Approved"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedules_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sro",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="core.sro",
                    ),
                ),
            ],
        ),
    ]
