# Generated by Django 5.2.7 on 2025-12-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_callout_status_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="callout",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("locked", "Locked"),
                    ("sro_activated", "SRO Activated"),
                    ("scheduled", "Scheduled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
