# Generated by Django 5.2.7 on 2025-12-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_callout_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sro",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("approved", "Approved"),
                    ("ready_for_scheduling", "Ready for Scheduling"),
                    ("scheduled", "Scheduled"),
                    ("assigned", "Assigned"),
                    ("active", "Active"),
                    ("executed", "Executed"),
                    ("qc_approved", "QC Approved"),
                    ("closed", "Closed"),
                    ("cancelled", "Cancelled"),
                ],
                default="created",
                max_length=30,
            ),
        ),
    ]
