# Generated by Django 5.2.7 on 2025-12-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_sro_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipment_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resouce_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="resource",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="type_of_equipment",
        ),
    ]
