# Generated by Django 5.2.7 on 2025-12-15 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_equipmenttype_resource_remove_schedule_resource_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedules",
                to="core.resource",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="type_of_equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedules",
                to="core.equipmenttype",
            ),
        ),
    ]
