# Generated by Django 5.2.7 on 2025-12-15 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_schedule_resource_schedule_type_of_equipment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resource",
            old_name="resouce_name",
            new_name="resource_name",
        ),
    ]
