# Generated by Django 5.2.7 on 2025-12-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_rename_resouce_name_resource_resource_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="scheduled_date",
            field=models.DateTimeField(default="2025-12-15 12:46:25.3191+04"),
            preserve_default=False,
        ),
    ]
