# Generated by Django 5.2.7 on 2025-12-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_schedule_scheduled_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("asset_code", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("on_duty", "On Duty"),
                            ("yellow", "Yellow"),
                            ("green", "Green"),
                            ("upgraded", "Upgraded"),
                            ("off_duty", "Off Duty"),
                            ("maintenance", "Maintenance"),
                            ("breakdown", "Breakdown"),
                        ],
                        default="on_duty",
                        max_length=30,
                    ),
                ),
                (
                    "cost_center",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("department", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "asset_group",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "physical_location",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "asset_main_category",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "asset_sub_category",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("asset_description", models.TextField(blank=True, null=True)),
                ("serial_no", models.CharField(blank=True, max_length=200, null=True)),
                ("part_no", models.CharField(blank=True, max_length=200, null=True)),
                ("mfg_serial", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "certificate",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_regular_inspection_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "next_due_date_regular_inspection",
                    models.DateField(blank=True, null=True),
                ),
                ("last_minor_service_date", models.DateField(blank=True, null=True)),
                (
                    "next_due_date_minor_service",
                    models.DateField(blank=True, null=True),
                ),
                ("last_major_service_date", models.DateField(blank=True, null=True)),
                (
                    "next_due_date_major_service",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "last_regular_inspection_km",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "last_regular_inspection_hours",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "last_regular_inspection_jobs",
                    models.FloatField(blank=True, null=True),
                ),
                ("last_minor_service_km", models.FloatField(blank=True, null=True)),
                ("last_minor_service_hours", models.FloatField(blank=True, null=True)),
                ("last_minor_service_jobs", models.FloatField(blank=True, null=True)),
                ("last_major_service_km", models.FloatField(blank=True, null=True)),
                ("last_major_service_hours", models.FloatField(blank=True, null=True)),
                ("last_major_service_jobs", models.FloatField(blank=True, null=True)),
                (
                    "next_regular_inspection_km",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "next_regular_inspection_jobs",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "next_regular_inspection_hour",
                    models.FloatField(blank=True, null=True),
                ),
                ("next_minor_service_km", models.FloatField(blank=True, null=True)),
                ("next_minor_service_jobs", models.FloatField(blank=True, null=True)),
                ("next_minor_service_hours", models.FloatField(blank=True, null=True)),
                ("next_major_service_jobs", models.FloatField(blank=True, null=True)),
                ("next_major_service_km", models.FloatField(blank=True, null=True)),
                ("next_major_service_hours", models.FloatField(blank=True, null=True)),
                ("third_party_comment", models.TextField(blank=True, null=True)),
                ("third_party_service_date", models.DateField(blank=True, null=True)),
                ("attachments1", models.TextField(blank=True, null=True)),
                (
                    "breakdown_maintenance_comment",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "next_third_party_service_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "maintenance_type",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("ncr_no", models.CharField(blank=True, max_length=150, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
