# Generated by Django 5.2.7 on 2025-12-22 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_asset"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeMaster",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_number", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_of_joining", models.DateField(blank=True, null=True)),
                ("grade", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "civil_id_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("civil_id_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "passport_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("passport_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "visa_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("visa_issue_date", models.DateField(blank=True, null=True)),
                ("visa_expiry_date", models.DateField(blank=True, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("blood_group", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "driving_license",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dl_expiry_date", models.DateField(blank=True, null=True)),
                ("tel_number", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "email_id",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "registered_bank_details",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("acc_number", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "employee_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contract_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "leave_schedule",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_appraisal", models.DateField(blank=True, null=True)),
                ("benefits", models.TextField(blank=True, null=True)),
                ("graduation", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("year_of_passing", models.PositiveIntegerField(blank=True, null=True)),
                ("university", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Single", "Single"),
                            ("Married", "Married"),
                            ("Divorced", "Divorced"),
                            ("Widowed", "Widowed"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "name_of_spouse",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("number_of_kids", models.PositiveIntegerField(blank=True, null=True)),
                ("name_kid_1", models.CharField(blank=True, max_length=255, null=True)),
                ("name_kid_2", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emergency_contact_tel",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "place_of_birth",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
