# Generated by Django 5.2.7 on 2025-12-23 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_assignedservice"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignedservice",
            name="schedule",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_service",
                to="core.schedule",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="schedule",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("planned", "Planned"),
                    ("approved", "Approved"),
                    ("assigned", "Assigned"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
