# Generated by Django 5.2.7 on 2025-12-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_assignedservice_schedule_alter_schedule_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignedservice",
            name="crew_required_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assignedservice",
            name="equipment_required_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
