# Generated by Django 5.2.7 on 2025-12-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_assignedservice_crew_required_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignedservice",
            name="employee",
        ),
        migrations.AddField(
            model_name="assignedservice",
            name="employees",
            field=models.ManyToManyField(
                related_name="assigned_services", to="core.employeemaster"
            ),
        ),
    ]
