# Generated by Django 5.2.7 on 2025-12-24 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_remove_assignedservice_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="callout",
            name="rig_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="callouts",
                to="core.rig",
            ),
        ),
        migrations.AlterField(
            model_name="callout",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("locked", "Locked"),
                    ("sro_activated", "SRO Activated"),
                    ("scheduled", "Scheduled"),
                    ("assigned", "Assigned"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
