# Generated by Django 5.2.7 on 2025-12-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_callout_rig_number_alter_callout_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="callout",
            name="ground_elevation_ref",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MSL", "MSL (Mean Sea Level)"),
                    ("GL", "GL (Ground Level)"),
                    ("KB", "KB (Kelly Bushing)"),
                    ("DF", "DF (Derrick Floor)"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="callout",
            name="h2s_level",
            field=models.CharField(
                blank=True,
                choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                default="",
                max_length=10,
            ),
        ),
    ]
