# Generated by Django 5.2.7 on 2025-12-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_callout_ground_elevation_ref_alter_callout_h2s_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="callout",
            name="pipe_selection_type",
            field=models.CharField(
                blank=True,
                choices=[("casing", "Casing"), ("drillpipe", "Drillpipe")],
                max_length=20,
                null=True,
            ),
        ),
    ]
