# Generated by Django 5.2.7 on 2025-12-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_callout_pipe_selection_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="callout",
            name="well_profile",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vertical", "Vertical"),
                    ("S-shape", "S-shape"),
                    ("J-shape", "J-shape"),
                    ("horizontal", "Horizontal"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
