# Generated by Django 5.2.7 on 2025-12-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_alter_callout_well_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="callout",
            name="casing_size_inch",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
    ]
