# Generated by Django 5.2.7 on 2025-12-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_callout_casing_size_inch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="well",
            name="ground_elevation_m",
        ),
    ]
