# Generated by Django 5.2.7 on 2025-12-28 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="callout",
            name="field_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="callouts",
                to="core.field",
            ),
        ),
    ]
