# Generated by Django 5.2.7 on 2025-12-29 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_alter_callout_field_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CasingSize",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.DecimalField(decimal_places=3, max_digits=6, unique=True),
                ),
                ("display_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="DrillpipeSize",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.DecimalField(decimal_places=3, max_digits=6, unique=True),
                ),
                ("display_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="MinimumIdSize",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.DecimalField(decimal_places=3, max_digits=6, unique=True),
                ),
                ("display_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="callout",
            name="casing_size_inch",
        ),
        migrations.RemoveField(
            model_name="callout",
            name="drillpipe_size_inch",
        ),
        migrations.RemoveField(
            model_name="callout",
            name="ground_elevation_ref",
        ),
        migrations.RemoveField(
            model_name="callout",
            name="minimum_id_inch",
        ),
        migrations.CreateModel(
            name="HoleSectionRelationship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allowed_casing_sizes",
                    models.ManyToManyField(
                        blank=True, related_name="hole_sections", to="core.casingsize"
                    ),
                ),
                (
                    "allowed_drillpipe_sizes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="hole_sections",
                        to="core.drillpipesize",
                    ),
                ),
                (
                    "hole_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships",
                        to="core.holesection",
                    ),
                ),
            ],
            options={
                "unique_together": {("hole_section",)},
            },
        ),
    ]
