# Generated by Django 5.2.7 on 2025-12-29 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_casingsize_drillpipesize_minimumidsize_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="callout",
            name="casing_size_inch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="callouts",
                to="core.casingsize",
            ),
        ),
        migrations.AddField(
            model_name="callout",
            name="drillpipe_size_inch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="callouts",
                to="core.drillpipesize",
            ),
        ),
        migrations.AddField(
            model_name="callout",
            name="ground_elevation_ref",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MSL", "MSL (Mean Sea Level)"),
                    ("GL", "GL (Ground Level)"),
                    ("KB", "KB (Kelly Bushing)"),
                    ("DF", "DF (Derrick Floor)"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="callout",
            name="minimum_id_inch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="callouts",
                to="core.minimumidsize",
            ),
        ),
    ]
