# Generated by Django 5.1.5 on 2026-01-04 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_callout_casing_size_inch_callout_drillpipe_size_inch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="callout",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="callouts",
                to="core.client",
            ),
        ),
    ]
