# Generated by Django 5.1.5 on 2026-01-04 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_callout_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="code",
        ),
    ]
