# Generated by Django 5.2.7 on 2026-01-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_remove_client_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="field_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
