# Generated by Django 5.2.7 on 2026-01-06 07:34

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_alter_field_field_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="field_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="field",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("field_name"),
                name="unique_field_name_lower",
            ),
        ),
    ]
