# Generated by Django 5.2.7 on 2026-01-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_alter_field_field_name_field_unique_field_name_lower"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sro",
            name="sro_number",
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
